### ISSUE TITLE
Is there a way add a footer or filter row  in datagrid in react-data-grid-react-window

### ISSUE THREAD

**Issue by it950** [microsoft/fluentui-contrib#209] opened 2024-08-05 07:39 UTC
In datagrid i want to do the following things: 
1, add a footer to DataGrid
2, add a filter row in DataGridHeader
3, drag and drop to change grid column header order like DetailList v8

**Comment by mainframev** [comment] 2024-09-17 19:39
Closing. Duplicate of [#32257](https://github.com/microsoft/fluentui/issues/32257)

**Closed by mainframev** 2024-09-17 19:39 UTC
